language: php

php:
  - 5.6
  - 7.0

before_script:
  - rm -R -f ./tests/tmp/*
  - composer self-update || echo "[ERROR] update-composer failed!"
  - composer install --no-interaction --optimize-autoloader

script:
  - ./vendor/bin/tester -s -j 32 -c ./tests/php.ini ./tests --coverage coverage.xml --coverage-src src

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config tests/.coveralls.yml
